language: node_js
matrix:
  include:
    - node_js: "0.11"
    - node_js: "0.11"
      env: "NODE_FLAGS='--harmony'"
    - node_js: "0.12"
    - node_js: "0.12"
      env: "NODE_FLAGS='--harmony'"
    - node_js: "v4"
    - node_js: "v6"
  fast_finish: true
before_install:
  - node -e 'new Promise(function(){}, function(){});' || npm install npm -g && npm install bluebird
script:
  - npm test $NODE_FLAGS
