language: node_js
matrix:
  include:
    - node_js: "0.8"
    - node_js: "0.10"
    - node_js: "0.11"
    - node_js: "0.11"
      env: "NODE_FLAGS='--harmony'"
    - node_js: "0.12"
    - node_js: "0.12"
      env: "NODE_FLAGS='--harmony'"
    - node_js: "iojs-v1.4.2"
    - node_js: "iojs"
  fast_finish: true
before_install:
  - iojs -e 'new Promise(function(){}, function(){});' || node -e 'new Promise(function(){}, function(){});' || npm install npm -g && npm install bluebird
script: 
  - npm test $NODE_FLAGS